# Generated by Django 4.2.2 on 2023-07-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='detail',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.TextField(default=''),
        ),
    ]
